#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
chruby ruby

settitle() {
    printf "\033k$1\033\\"
}
zsh_prompt_command() {
    prompt_agnoster_pwd
    settitle "`hostname -s`:${_prompt_agnoster_pwd}"
}

precmd() { zsh_prompt_command }
